config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'contacts#index', as: 'home'
  resource :users
  resource :contacts
  get '/contacts/index' => 'contacts#index'
  get '/contacts/extended' => 'contacts#extended'
  get '/email/confirmation' => 'sessions#emailverification'
  get '/forgot/password' => 'sessions#forgotpassword'
  post '/forgot/password' => 'sessions#sendforgotpasswordmail'
  get '/reset/password' => 'sessions#resetpassword'
  post '/reset/password' => 'sessions#resetpasswordchange'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/signup' => 'sessions#signupuser'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'sessions#signup'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authorize

  def index
    @contacts = Contact.where(user_id: current_user.id).order(:created_at => "DESC")
  end

  def create

    @contact = Contact.new(contact_params)
    if params[:contact][:name] == ''
      flash[:warning] = "Please enter name."
    end
    if params[:contact][:name] != '' && params[:contact][:phone_no] == ''
      flash[:warning] = "Please enter phone number."
    end
    if params[:contact][:name] != '' && params[:contact][:phone_no] != '' && @contact.save
      redirect_to contacts_index_path
    else
      redirect_to controller: 'contacts', action: 'new'
    end
  end

  def new
    @contact = Contact.new
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def extended
    @usercontacts = Contact.select(:phone_no).where(user_id: current_user.id)
    @usercontactids = Contact.where("user_id IN (?) and phone_no!=?", User.select(:id).where("mobile IN (?)", @usercontacts),current_user.mobile)
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    redirect_to contacts_index_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to contacts_index_path
  end

  private def contact_params
    params.require(:contact).permit(:name, :phone_no, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  require 'digest/md5'

  def create
    if params[:email] == ''
      flash[:warning] = "Please enter email."
    end
    if params[:email] != '' && params[:password] == ''
      flash[:warning] = "Please enter password."
    end
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password]) && user.email_verified
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      if !user.email_verified
        flash[:warning] = "Your email is not verified."
      else
        flash[:warning] = "Invalid login credentials."
      end
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  def signup
    @user = User.new
  end

  def emailverification
    user = User.find_by_email(params[:token])
    if user && user.update_attribute(:email_verified, 1)
      flash[:warning] = "Your email verified,You can login now."
      redirect_to '/login'
    else
      flash[:warning] = "Unable to verify your email."
      redirect_to '/signup'
    end
  end

  def forgotpassword

  end

  def resetpasswordchange
    if !params[:user] || !params[:user][:reset_token] || params[:user][:reset_token] == ''
      redirect_to '/login'
    else
      user = User.find_by_reset_token(params[:user][:reset_token])
      if user && user.update_attribute(:password, params[:user][:password])
        flash[:warning] = "Password reset successfully."
        redirect_to '/login'
      else
        flash[:warning] = "User not found."
        redirect_to '/signup'
      end
    end
  end

  def sendforgotpasswordmail
    user = User.find_by_email(params[:email])
    if user && user.update_attribute(:reset_token, Digest::MD5.hexdigest(user.email + user.name + user.mobile))
      ResetPasswordMailer.reset_password_email(user).deliver
      flash[:warning] = "Reset password link has been sent to your email."
      redirect_to '/login'
    else
      flash[:warning] = "Email not found."
      redirect_to forgot_password_path
    end
  end

  def resetpassword
    user = User.find_by_reset_token(params[:token])
    if user
      @token = params[:token]
    else
      flash[:warning] = "Account not found."
      redirect_to '/login'
    end
  end

  def signupuser
    @allowtoregister = true
    @user = User.new(user_params)
    if params[:user][:password] != params[:user][:password_confirmation]
      flash[:warning] = "Password and confirm password didn't match."
      @allowtoregister = false
    end
    if params[:user][:password] == ''
      flash[:warning] = "Password is required."
      @allowtoregister = false
    end
    if params[:user][:mobile] == ''
      flash[:warning] = "Mobile number is required."
      @allowtoregister = false
    end
    if params[:user][:email] == ''
      flash[:warning] = "Email is required."
      @allowtoregister = false
    end
    if params[:user][:name] == ''
      flash[:warning] = "Name is required."
      @allowtoregister = false
    end
    if User.find_by_email(params[:user][:email])
      flash[:warning] = "Email already exist."
      @allowtoregister = false
    end
    respond_to do |format|
      if @allowtoregister && @user.save
        UserMailer.user_email(@user).deliver

        format.html {redirect_to '/login', notice: 'User created successfully.Please verify your email to login.'}
      else
        format.html {render :new}
      end
    end
  end

  private def user_params
    params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        # Sends email to user when user is created.
        UserMailer.user_email(@user).deliver

        format.html {redirect_to '/', notice: 'User was successfully created.'}
        format.json {render :show, status: :created, location: @user}
      else
        format.html {render :new}
        format.json {render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to controller: 'users', action: 'index'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to controller: 'users', action: 'index'
  end

  private def user_params
    params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">
        <h4>Edit Contact</h4>

      </div>
      <div class="card-body">
        <div class="basic-form col-md-5">
          <%= form_for :contact, url: contacts_path(:id => @contact.id), method: :patch do |f| %>
            <div class="form-group">
              <p>
                <%= f.label :name %><br>
                <%= f.text_field(:name, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :phone_no %><br>
                <%= f.text_field(:phone_no, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <p>
              <%= f.submit({:class => 'btn btn-info'}) %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/extended.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">

        <h4>Extended Contact list </h4>
      </div>
      <div class="card-body extended-contact-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Phone No</th>
            </tr>
            </thead>
            <tbody>

            <% @usercontactids.each do |contact| %>
              <tr>
                <td><%= contact.name %></td>
                <td><span><%= contact.phone_no %></span></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">

        <h4>Contact list </h4>
        <div class="row pull-right">
          <div class="add-user-btn">
            <%= link_to 'Extended contacts', contacts_extended_path, :class => 'btn btn-info' %>
            <%= link_to 'Add new contacts', new_contacts_path, :class => 'btn btn-info' %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Mobile</th>
              <th></th>
            </tr>
            </thead>
            <tbody>

            <% @contacts.each do |contact| %>
              <tr>
                <td><%= contact.name %></td>
                <td><span><%= contact.phone_no %></span></td>
                <td>
                  <a href=""><%= link_to 'Edit', edit_contacts_path(:id => contact.id), :class => 'btn btn-info btn-edit' %></a>
                  <a href=""><%= link_to 'Delete', contacts_path(:id => contact.id),
                                         method: :delete,
                                         data: {confirm: 'Are you sure?'},
                                         :class => 'btn btn-danger' %></a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">
        <h4>Add new contact</h4>

      </div>
      <div class="card-body">
        <div class="basic-form col-md-5">
          <%= form_for :contact, url: '/contacts' do |f| %>
            <div class="form-group">
              <p>
                <%= f.label :name %><br>
                <%= f.text_field(:name, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :phone_no %><br>
                <%= f.text_field(:phone_no, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <p>
              <%= f.submit({:class => 'btn btn-info'}) %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RORApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="management-theme data-entry-multiple-body">
<nav class="navbar navbar-default navbar-fixed-top management-navbar">
  <div class="container-fluid justify-content-center">
    <div class="row new">
      <div class="col-md-5">
        <%= link_to "Contacts", contacts_index_path %>
      </div>
<!--      <div class="col-md-2">-->
        <!--        <a class="navbar-brand" href="../users#index">-->
<!--        <div class="logo-icon-container">-->
          <!--            <img src="bjp.png" class="logo-icon img-responsive" alt="">-->
          <%#= link_to image_tag('bjp.png'), root_path %>
          <%#= image_tag("bjp.png", :alt => "logo", :class => 'logo-icon img-responsive') %>
          <%# end %>
          <%#= link_to home_path do %>
            <%#= image_tag('bjp.png', :alt => "logo", :class => 'logo-icon img-responsive') %>
          <%# end %>
<!--        </div>-->
        <!--        </a>-->
<!--      </div>-->
      <div class="col-md-5 auth-action">
        <% if current_user %>
          Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
        <% else %>
          <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<!--<div class="container">-->
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">
        <h4>Edit User</h4>

      </div>
      <div class="card-body">
        <div class="basic-form">
          <%= form_for :user, url: users_path(:id => @user.id), method: :patch do |f| %>
            <div class="form-group">
              <p>
                <%= f.label :name %><br>
                <%= f.text_field(:name, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :email %><br>
                <%= f.text_field(:email, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :mobile %><br>
                <%= f.text_field(:mobile, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <p>
              <%= f.submit({:class => 'btn btn-info'}) %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">

        <h4>Users list </h4>
        <div class="row pull-right">
          <div class="add-user-btn">
            <%#= link_to 'Download Excel', download_excel_path(format: "xls"), :class => 'btn btn-danger' %>
            <%= link_to 'Add new user', new_users_path, :class => 'btn btn-info' %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Mobile</th>
              <th></th>
            </tr>
            </thead>
            <tbody>

            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><span><%= user.email %></span></td>
                <td><span><%= user.mobile %></span></td>
                <td>
                  <a href=""><%= link_to 'Edit', edit_users_path(:id => user.id), :class => 'btn btn-info btn-edit' %></a>
                  <a href=""><%= link_to 'Delete', users_path(:id => user.id),
                                         method: :delete,
                                         data: {confirm: 'Are you sure?'},
                                         :class => 'btn btn-danger' %></a>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-title">
        <h4>Add new user</h4>

      </div>
      <div class="card-body">
        <div class="basic-form">
          <%= form_for :user, url: '/users' do |f| %>
            <div class="form-group">
              <p>
                <%= f.label :name %><br>
                <%= f.text_field(:name, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :email %><br>
                <%= f.text_field(:email, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :mobile %><br>
                <%= f.text_field(:mobile, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :password %><br>
                <%= f.password_field(:password, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <div class="form-group">
              <p>
                <%= f.label :password_confirmation %><br>
                <%= f.password_field(:password_confirmation, {:class => 'form-control input-flat'}) %>
              </p>
            </div>
            <p>
              <%= f.submit({:class => 'btn btn-info'}) %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>